/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala.pkg1.pkg0;

/**
 *
 * @author mario
 */
public class GameBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameBoardPanel
     */
    public GameBoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftBankPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rightBankPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pocketsPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        leftBankPanel.setLayout(new java.awt.GridLayout());

        jButton1.setText("jButton1");
        leftBankPanel.add(jButton1);

        add(leftBankPanel, java.awt.BorderLayout.LINE_START);

        rightBankPanel.setLayout(new java.awt.GridLayout());

        jButton2.setText("jButton2");
        rightBankPanel.add(jButton2);

        add(rightBankPanel, java.awt.BorderLayout.LINE_END);

        pocketsPanel.setLayout(new java.awt.GridLayout(2, 6));

        jButton3.setText("jButton3");
        pocketsPanel.add(jButton3);

        jButton4.setText("jButton4");
        pocketsPanel.add(jButton4);

        jButton5.setText("jButton5");
        pocketsPanel.add(jButton5);

        jButton6.setText("jButton6");
        pocketsPanel.add(jButton6);

        jButton7.setText("jButton7");
        pocketsPanel.add(jButton7);

        jButton8.setText("jButton8");
        pocketsPanel.add(jButton8);

        jButton9.setText("jButton9");
        pocketsPanel.add(jButton9);

        jButton10.setText("jButton10");
        pocketsPanel.add(jButton10);

        jButton11.setText("jButton11");
        pocketsPanel.add(jButton11);

        jButton12.setText("jButton12");
        pocketsPanel.add(jButton12);

        jButton13.setText("jButton13");
        pocketsPanel.add(jButton13);

        jButton14.setText("jButton14");
        pocketsPanel.add(jButton14);

        add(pocketsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel leftBankPanel;
    private javax.swing.JPanel pocketsPanel;
    private javax.swing.JPanel rightBankPanel;
    // End of variables declaration//GEN-END:variables
}
