/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala.pkg1.pkg0;

import mancala.pkg1.pkg0.MainFrame;

/**
 *
 * @author Dung T Nguyen
 */
public class MainMenuPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    
    public MainMenuPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }
    
    public void setMainFrame(MainFrame mainFrame){
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTitlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        menuButtonsPanel = new javax.swing.JPanel();
        playGameButton = new javax.swing.JButton();
        aboutMancalaButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("The Mancala Effect");

        javax.swing.GroupLayout menuTitlePanelLayout = new javax.swing.GroupLayout(menuTitlePanel);
        menuTitlePanel.setLayout(menuTitlePanelLayout);
        menuTitlePanelLayout.setHorizontalGroup(
            menuTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        menuTitlePanelLayout.setVerticalGroup(
            menuTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        add(menuTitlePanel, java.awt.BorderLayout.PAGE_START);

        menuButtonsPanel.setLayout(new java.awt.GridLayout(4, 1));

        playGameButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playGameButton.setText("Play Game");
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(playGameButton);

        aboutMancalaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aboutMancalaButton.setText("About Mancala");
        aboutMancalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMancalaButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(aboutMancalaButton);

        optionsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        optionsButton.setText("Options");
        menuButtonsPanel.add(optionsButton);

        exitButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(exitButton);

        add(menuButtonsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed
        this.mainFrame.playGame();
    }//GEN-LAST:event_playGameButtonActionPerformed

    private void aboutMancalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMancalaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMancalaButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutMancalaButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel menuButtonsPanel;
    private javax.swing.JPanel menuTitlePanel;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton playGameButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables


}
