/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala.pkg1.pkg0;

import java.awt.BorderLayout;
import mancala.pkg1.pkg0.GameBoardPanel;
import mancala.pkg1.pkg0.MancalaGame;

/**
 *
 * @author Dung T Nguyen
 */
public class MainFrame extends javax.swing.JFrame {
    private MancalaGame mancalaGame;
    private MainMenuPanel mainMenu;
    private GameBoardPanel game;
    
    public MainFrame() {
        initComponents();
        this.mancalaGame = new MancalaGame();
        this.mainMenu = new MainMenuPanel();
        this.mancalaGame.start();
        this.mainMenu.setMainBoard(this);
        this.getContentPane().add(this.mainMenu, BorderLayout.CENTER);
        this.setSize(700, 500);
    }
    
    public MancalaGame getMancalaGame(){
        return this.mancalaGame;
    }
    
    public void gameConstructor(){
        this.game = new GameBoardPanel();
        this.game.setMainBoard(this);
        this.game.setMancalaGame(mancalaGame);
        this.game.updateStonesForPlayerOne();
        this.game.updateStonesForPlayerTwo();
        this.game.updateP1Score();
        this.game.updateP2Score();
        this.game.updateButtonsP1(true);
        this.game.updateButtonsP2(false);
    }
    
    public void playGame(){
        this.getContentPane().remove(this.mainMenu);
        gameConstructor();
        this.getContentPane().add(this.game, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
